name:                examples
version:             0.1.0.0
#synopsis:
homepage:            https://github.com/Siprj/examples#readme
license:             MIT
author:              Sipr
maintainer:          sipr.jan@gmail.com
copyright:           2019 Sipr
category:            examples
extra-source-files:
- README.md

description: >
    Please see the README on Github at 
    <https://github.com/Siprj/examples#readme>

flags:
  pedantic:
    description: Pass additional warning flags and -Werror to GHC.
    default: True
    manual: True

dependencies:
  - base >= 4.7 && < 5
  - symbols

executables:
  examples:
    main: Main.hs
    source-dirs: src
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -Wmissing-import-lists
