name:                live-coding
version:             0.1.0.0
#synopsis:
homepage:            https://github.com/Siprj/examples#readme
license:             MIT
author:              Sipr
maintainer:          sipr.jan@gmail.com
copyright:           2019 Sipr
category:            examples

# description:

dependencies:
  - base >= 4.7 && < 5
  - symbols
  - transformers

executables:
  live-coding:
    main: Main.hs
    source-dirs: src
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
